language: ruby
rvm:
- 2.3.0
- 2.3.1

cache: bundler

deploy:
  provider: rubygems
  api_key:
    secure: "YymT9pXiLoxk3ceH7SHHPXgxAZc1Hu2HIBp8saryrOdhb0RZ1yYTyG0lIDs30YG85UCxVMN9rwNZrJOTE4GsZNBuTubEK+k9f701pvP6hnmAtUUUt1QwAMi9sz5IKURk1SPI7R/iRTkOcCyM6mhKSC/ItjQfuLsWOCE8snugzKi0cQC3vSonIBal5iJjgeYZkuncZOJcYSyuIfbQaZBBMu7uBGQrykg8fLWX9Sreh9KmFRb9A3FiuH0kroQCrivl/d/X7u4a3WmFXR0Bqj39+C2B4LRuUJ37PHkXgogvpgNyeR/+t4kTWfv96aa3NirxaFc3LB0Zl9ZdEBrNURN+awLmyBt8WmI25NahydGsZMuwWMMXhjx1NWfYGdI53ZAwA8fOsBASqntvtkAWLSpr8Lekv3S844545zHtqeYtYY1egWZ/aHwAckkfRoKJOAyStrN59DHKquJPRdhMEPKM23YwtUrXmjoJ+B/KC/Z6bFiWnDvq5V7FMt3twGmwabHGD+cSglTCdHbpEEbfZYV24NBBclzXhRtAgVUG3obcfJvKPY/f889JlIpWzRdxu74G8K9uxq3ku21EIfWIMKv3Nx4yPyKDdu60RbkUyq7VwvWyO7WgBhU+Vh1pVqMVAe4EErJTqMCXlJulzy8oE3IOhB1oUHyfxTE+dimwX6je4Qc="
  gem: hash_kit
  on:
    tags: true
    condition: "$TRAVIS_RUBY_VERSION == 2.3.1"

