language: ruby
rvm:
  - 2.3.5
cache: bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: rubygems
  api_key:
    secure: YymT9pXiLoxk3ceH7SHHPXgxAZc1Hu2HIBp8saryrOdhb0RZ1yYTyG0lIDs30YG85UCxVMN9rwNZrJOTE4GsZNBuTubEK+k9f701pvP6hnmAtUUUt1QwAMi9sz5IKURk1SPI7R/iRTkOcCyM6mhKSC/ItjQfuLsWOCE8snugzKi0cQC3vSonIBal5iJjgeYZkuncZOJcYSyuIfbQaZBBMu7uBGQrykg8fLWX9Sreh9KmFRb9A3FiuH0kroQCrivl/d/X7u4a3WmFXR0Bqj39+C2B4LRuUJ37PHkXgogvpgNyeR/+t4kTWfv96aa3NirxaFc3LB0Zl9ZdEBrNURN+awLmyBt8WmI25NahydGsZMuwWMMXhjx1NWfYGdI53ZAwA8fOsBASqntvtkAWLSpr8Lekv3S844545zHtqeYtYY1egWZ/aHwAckkfRoKJOAyStrN59DHKquJPRdhMEPKM23YwtUrXmjoJ+B/KC/Z6bFiWnDvq5V7FMt3twGmwabHGD+cSglTCdHbpEEbfZYV24NBBclzXhRtAgVUG3obcfJvKPY/f889JlIpWzRdxu74G8K9uxq3ku21EIfWIMKv3Nx4yPyKDdu60RbkUyq7VwvWyO7WgBhU+Vh1pVqMVAe4EErJTqMCXlJulzy8oE3IOhB1oUHyfxTE+dimwX6je4Qc=
  gem: hash_kit
  on:
    tags: true
    condition: "$TRAVIS_RUBY_VERSION == 2.3.5"
    repo: Sage/class_kit
env:
  global:
    secure: lI5jMmJJuZm3Z+MHpPxD+85LsGbtevjyVvU0HCMqHol16eXLqUcMFNM13r/loYExNHKB4jMPECOXcgdY5vYlMuLb7vWWQdvb9gwGodkibtqQk069d4UapMiBXzzEddE/Mm0q7dur1MBgwBMhES6a9WJhJneYCd0qeWwgB0KrkjAspfvRsFJQ8euQ8tD5cjzrFE4UL/lIPrnTNEuurGZz4Zmu06bD1et4nRannC7Ms0BsOUfZWsjKsBCZuS+ap1d1J9G+6QN8pnGfwN9W/+bYuJ/B9zMjGIGH/NyGg/uS68eX/hFk5XReAnS9RIlY8Lfo3SALUlZ+Sq3zjTctlmde+yRpHObRGR/QXX4zlZ/php/lrurYmZqMQxHvHPoF9TSliJzCGzIEBACcyX8rAFhtgyRiEJ3hNd6X1Xf/qOe9j+4/PseGQYWgP9wSaLX5sT3BLiEKTjl4V+eFT+MK8LFmdIfgbnaNpb9EnNVvEZwQpE3SXE3BoBVwkkEPbhwHpx2uy3a23Y4vsp0Jo4+lWkTG8YkZGz2+L62pOLU803SktN4wbVSA4kdK6VXGW1wzt2LH8CWlbWaLvbNczWCc+xU8QqBqjvjSQGdgDGISLCZxz7gHrT2g+cHj2Qd6BdMX3uHudXQvwQdIOmAeshiz4qfnbup7k40fab7jHuL62Icibss=
