services:
  gem_test_runner:
    image: ruby:2.7.8-bullseye
    container_name: gem_test_runner
    command: bash -c "while true; do echo 'Container is running...'; sleep 2; done"
    volumes:
        - ../:/gem_src
