name: RSpec
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: |
          cd  script
          docker-compose up -d
          docker exec gem_test_runner bash -c "cd gem_src && bundle install && bundle exec rspec && exit"

      - name: Code Coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          prefix: '/gem_src'
          debug: true
          verifyDownload: true
          coverageLocations: |
            ${{github.workspace}}/coverage/.resultset.json:simplecov
