name: RSpec
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: |
          docker-compose up -d
          docker exec gem_test_runner bash -c "cd gem_src && bundle install && bundle exec rspec"
          ls -a ${{github.workspace}}/coverage
          cat ${{github.workspace}}/coverage/.resultset.json

      - name: Code Coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          debug: true
          coverageLocations: |
            ${{github.workspace}}/coverage/coverage.json:simplecov
          prefix: /gem_src
          verifyDownload: true
